---

- hosts: windows

  vars_files: print_vars.yml
  gather_facts: yes
  tasks:

    - name: Instalar servicios de impresion
      win_feature:
        name: Print-Services
        state: absent
        include_sub_features: yes

    - name: Administrar impresoras
      win_shell:
        pnputil.exe /add-driver "{{driver_ruta}}"
        Add-PrinterDriver -Name "'{{driver_nombre}}'"
        Add-PrinterPort -Name "'{{puerto_nombre}}'" -PrinterHostAddress "'{{puerto_impresora}}'"
        Add-printer -Name "'{{driver_nombre}}'" -DriverName "'{{driver_nombre}}'" -shared -ShareName "'{{driver_nombre}}'" -PortName "'{{puerto_nombre}}'" -Published
